# Generated by Django 5.2.9 on 2025-12-11 11:04

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_destinationspage_remove_homepage_services_preview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinationspage',
            name='Destinations',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='Destinations_preview',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='Destinations_preview_intro',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='Destinations_preview_title',
        ),
        migrations.AddField(
            model_name='homepage',
            name='info_categories',
            field=wagtail.fields.StreamField([('info_category', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Titre de la catégorie', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Description', 'required': True}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('location', 'Lieux emblématiques'), ('culture', 'Histoire et culture'), ('leaf', 'Conseils pratiques'), ('star', 'Faits intéressants')], 'help_text': 'Icône associée'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image optionnelle', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('icon', 2), ('image', 3)]], {})}, verbose_name="Bloc 'Ce que vous trouverez'"),
        ),
        migrations.AlterField(
            model_name='destinationspage',
            name='intro_subtitle',
            field=models.TextField(blank=True, default='Voici un exemple de section destinations que vous pouvez adapter.', help_text="Ex : 'Voici un exemple de section destinations...'", verbose_name='Texte d’intro'),
        ),
        migrations.AlterField(
            model_name='destinationspage',
            name='intro_title',
            field=models.CharField(default='Nos destinations', max_length=150, verbose_name='Titre principal'),
        ),
        migrations.AddField(
            model_name='destinationspage',
            name='destinations',
            field=wagtail.fields.StreamField([('destination', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Petit texte au-dessus (ex : 01, 02, 03...)', 'label': 'Badge / numéro', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Titre du destination', 'max_length': 120, 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Description courte', 'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image ou icône illustrant le destination (format horizontal de préférence).', 'label': 'Image du destination', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Point clé'}), 5: ('wagtail.blocks.ListBlock', (4,), {'label': 'Liste de points clés (bullet points)', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('badge', 0), ('title', 1), ('description', 2), ('image', 3), ('features', 5)]], {})}, help_text='Liste complète des destinations proposés.', verbose_name='destinations'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='destinations_preview',
            field=wagtail.fields.StreamField([('destination', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Petit texte au-dessus (ex : 01, 02, 03...)', 'label': 'Badge / numéro', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Titre du destination', 'max_length': 120, 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Description courte', 'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image ou icône illustrant le destination (format horizontal de préférence).', 'label': 'Image du destination', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Point clé'}), 5: ('wagtail.blocks.ListBlock', (4,), {'label': 'Liste de points clés (bullet points)', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('badge', 0), ('title', 1), ('description', 2), ('image', 3), ('features', 5)]], {})}, verbose_name='destinations à afficher sur l’accueil (aperçu)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='destinations_preview_intro',
            field=models.TextField(blank=True, default='Un aperçu rapide de nos destinations.', help_text='Petite phrase pour introduire les destinations.', verbose_name='Texte d’intro de la section destinations (accueil)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='destinations_preview_title',
            field=models.CharField(default='Nos destinations', max_length=150, verbose_name='Titre de la section destinations (accueil)'),
        ),
    ]
