# Generated by Django 5.2.9 on 2025-12-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_destinationspage_destinations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='contact_address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Adresse'),
        ),
    ]
