# Generated by Django 5.2.9 on 2025-12-12 15:22

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_contactpage_contact_address'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationspage',
            name='destinations',
            field=wagtail.fields.StreamField([('destination', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Petit texte au-dessus (ex : 01, 02, 03...)', 'label': 'Badge / numéro', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Titre du destination', 'max_length': 120, 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Description courte', 'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image ou icône illustrant le destination (format horizontal de préférence).', 'label': 'Image du destination', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Point clé'}), 5: ('wagtail.blocks.ListBlock', (4,), {'label': 'Liste de points clés (bullet points)', 'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('europe', 'Europe'), ('asie', 'Asie'), ('amerique', 'Amérique'), ('afrique', 'Afrique'), ('oceanie', 'Océanie')], 'help_text': 'Choisir le continent de la destination', 'label': 'Continent'}), 7: ('wagtail.blocks.StructBlock', [[('badge', 0), ('title', 1), ('description', 2), ('image', 3), ('features', 5), ('continent', 6)]], {})}, help_text='Liste complète des destinations proposés.', verbose_name='destinations'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='destinations_preview',
            field=wagtail.fields.StreamField([('destination', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Petit texte au-dessus (ex : 01, 02, 03...)', 'label': 'Badge / numéro', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Titre du destination', 'max_length': 120, 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Description courte', 'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image ou icône illustrant le destination (format horizontal de préférence).', 'label': 'Image du destination', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Point clé'}), 5: ('wagtail.blocks.ListBlock', (4,), {'label': 'Liste de points clés (bullet points)', 'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('europe', 'Europe'), ('asie', 'Asie'), ('amerique', 'Amérique'), ('afrique', 'Afrique'), ('oceanie', 'Océanie')], 'help_text': 'Choisir le continent de la destination', 'label': 'Continent'}), 7: ('wagtail.blocks.StructBlock', [[('badge', 0), ('title', 1), ('description', 2), ('image', 3), ('features', 5), ('continent', 6)]], {})}, verbose_name='destinations à afficher sur l’accueil (aperçu)'),
        ),
        migrations.CreateModel(
            name='DestinationDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('sous_titre', models.CharField(blank=True, max_length=250, verbose_name='Sous-titre')),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='Description')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
