# Generated by Django 5.2.9 on 2025-12-15 12:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_destinationspage_destinations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationdetailpage',
            name='contenu',
            field=wagtail.fields.StreamField([('paragraphe', 0), ('image', 1), ('citation', 2)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.BlockQuoteBlock', (), {})}, verbose_name='Blocs de contenu'),
        ),
    ]
